os: linux
sudo: false
language: c
dist: trusty

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
  coverity_scan:
    project:
      name: "wuorg/wulk"
      description: "Build submitted via Travis CI"
    notification_email: lucas.abel@yandex.com
    build_command_prepend: "mkdir build && cd build && cmake .."
    build_command:   "make && cd .."
    branch_pattern: coverity_scan

before_install: mkdir build && cd build && cmake ..
install: make && cd ..
script: echo "hey, i'm just a coverity scan build"
